### ISSUE TITLE
Don't break the constructor chain

### ISSUE THREAD

**Issue by rajasekarm** [jayzamazing/Pirate-Bartender-Project#2]
``` javascript
  Questions.prototype = {
         getQuestion: function(index) {
             return this.listOfQuestions[index];
         }
     };
```

to 

``` javascript
  Questions.prototype = {
        constructor: Questions
         getQuestion: function(index) {
             return this.listOfQuestions[index];
         }
     };
```

Hope this is clear, If you need explanation let me know.

**Comment by jayzamazing** [comment]
Without offering a good explanation as to how it is breaking the constructor chain, I fail to see how this is improving the code. Please either offer a better explanation or documentation so I can see why the improvement is needed.

**Comment by jayzamazing** [comment]
Closing issue based on the following post: http://stackoverflow.com/questions/4012998/what-it-the-significance-of-the-javascript-constructor-property
